// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantManagement.API.Data;

#nullable disable

namespace RestaurantManagement.API.Migrations
{
    [DbContext(typeof(RestaurantDbContext))]
    [Migration("20260915122859_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestaurantManagement.API.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Apellido = "Perez",
                            Cedula = "1710034065",
                            Email = "juan.perez@example.com",
                            Nombre = "Juan",
                            Telefono = "0991234567"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Apellido = "Lopez",
                            Cedula = "0926629913",
                            Email = "maria.lopez@example.com",
                            Nombre = "Maria",
                            Telefono = "0987654321"
                        });
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.DetallePedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<int>("PlatoId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("PlatoId");

                    b.ToTable("DetallesPedido");
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.Mesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("NumeroMesa")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NumeroMesa")
                        .IsUnique();

                    b.ToTable("Mesas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Capacidad = 2,
                            Estado = 0,
                            NumeroMesa = 1
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Capacidad = 4,
                            Estado = 0,
                            NumeroMesa = 2
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Capacidad = 6,
                            Estado = 0,
                            NumeroMesa = 3
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Capacidad = 8,
                            Estado = 0,
                            NumeroMesa = 4
                        });
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MesaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("MesaId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.Plato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Platos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Categoria = "Platos Fuertes",
                            Descripcion = "Sopa tradicional de albacora y camarón con yuca y cebolla curtida",
                            Disponible = true,
                            Nombre = "Encebollado Mixto",
                            Precio = 5.50m
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Categoria = "Platos Fuertes",
                            Descripcion = "Trozos de lomo de res salteados con cebolla, tomate y papas fritas",
                            Disponible = true,
                            Nombre = "Lomo Saltado",
                            Precio = 8.00m
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Categoria = "Mariscos",
                            Descripcion = "Arroz marinado sazonado con vegetales y camarones frescos",
                            Disponible = true,
                            Nombre = "Arroz con Camarones",
                            Precio = 7.50m
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Categoria = "Bebidas",
                            Descripcion = "Bebida refrescante de fruta natural (500ml)",
                            Disponible = true,
                            Nombre = "Jugo Natural de Naranjilla",
                            Precio = 1.50m
                        });
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.DetallePedido", b =>
                {
                    b.HasOne("RestaurantManagement.API.Models.Pedido", "Pedido")
                        .WithMany("Detalles")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantManagement.API.Models.Plato", "Plato")
                        .WithMany("DetallesPedido")
                        .HasForeignKey("PlatoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Plato");
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.Pedido", b =>
                {
                    b.HasOne("RestaurantManagement.API.Models.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestaurantManagement.API.Models.Mesa", "Mesa")
                        .WithMany("Pedidos")
                        .HasForeignKey("MesaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cliente");

                    b.Navigation("Mesa");
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.Cliente", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.Mesa", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.Pedido", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.Plato", b =>
                {
                    b.Navigation("DetallesPedido");
                });
#pragma warning restore 612, 618
        }
    }
}
