// <auto-generated />
using System;
using AgenciaPublicidad.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgenciaPublicidad.Migrations
{
    [DbContext(typeof(AgenciaDbContext))]
    [Migration("20260710125033_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgenciaPublicidad.Models.Campana", b =>
                {
                    b.Property<int>("campana_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("campana_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("campana_id"));

                    b.Property<int>("cliente_id")
                        .HasColumnType("int")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("fecha_inicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_inicio");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("presupuesto")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("presupuesto");

                    b.HasKey("campana_id");

                    b.HasIndex("cliente_id");

                    b.ToTable("Campanas");
                });

            modelBuilder.Entity("AgenciaPublicidad.Models.Cliente", b =>
                {
                    b.Property<int>("cliente_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cliente_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cliente_id"));

                    b.Property<string>("contacto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contacto");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("nombre_empresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre_empresa");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("telefono");

                    b.HasKey("cliente_id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("AgenciaPublicidad.Models.Disenador", b =>
                {
                    b.Property<int>("disenador_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("disenador_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("disenador_id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("especialidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("especialidad");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("telefono");

                    b.HasKey("disenador_id");

                    b.ToTable("Disenadores");
                });

            modelBuilder.Entity("AgenciaPublicidad.Models.Entregable", b =>
                {
                    b.Property<int>("entregable_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("entregable_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("entregable_id"));

                    b.Property<int>("campana_id")
                        .HasColumnType("int")
                        .HasColumnName("campana_id");

                    b.Property<int>("disenador_id")
                        .HasColumnType("int")
                        .HasColumnName("disenador_id");

                    b.Property<DateTime>("fecha_entrega")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_entrega");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tipo");

                    b.HasKey("entregable_id");

                    b.HasIndex("campana_id");

                    b.HasIndex("disenador_id");

                    b.ToTable("Entregables");
                });

            modelBuilder.Entity("AgenciaPublicidad.Models.Campana", b =>
                {
                    b.HasOne("AgenciaPublicidad.Models.Cliente", "Cliente")
                        .WithMany("Campanas")
                        .HasForeignKey("cliente_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("AgenciaPublicidad.Models.Entregable", b =>
                {
                    b.HasOne("AgenciaPublicidad.Models.Campana", "Campana")
                        .WithMany("Entregables")
                        .HasForeignKey("campana_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgenciaPublicidad.Models.Disenador", "Disenador")
                        .WithMany("Entregables")
                        .HasForeignKey("disenador_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campana");

                    b.Navigation("Disenador");
                });

            modelBuilder.Entity("AgenciaPublicidad.Models.Campana", b =>
                {
                    b.Navigation("Entregables");
                });

            modelBuilder.Entity("AgenciaPublicidad.Models.Cliente", b =>
                {
                    b.Navigation("Campanas");
                });

            modelBuilder.Entity("AgenciaPublicidad.Models.Disenador", b =>
                {
                    b.Navigation("Entregables");
                });
#pragma warning restore 612, 618
        }
    }
}
